// ENVIRONMENT VARIABLES KEYS
export const MONGODBURI_AWS_SECRET_NAME = 'MONGODBURI_AWS_SECRET_NAME';
export const MONGODBURI_AWS_SECRET_KEY = 'MONGODBURI_AWS_SECRET_KEY';
export const JWT_SECRET_AWS_SECRET_NAME = 'JWT_SECRET_AWS_SECRET_NAME';
export const JWT_SECRET_AWS_SECRET_KEY = 'JWT_SECRET_AWS_SECRET_KEY';
export const JWT_EXPIRATION = 'JWT_EXPIRATION';
export const AWS_S3_REGION = 'AWS_S3_REGION';
